checkout/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^adicionar/(?P<slug>[\w_-]+)/$', views.CreateCartItemView.as_view(), name='create_cartitem'),
    url(r'^carrinho/$', views.CartItemView.as_view(), name='cart_item'),
    url(r'^finalizando/$', views.CheckoutView.as_view(), name='checkout'),
    url(r'^meus-pedidos/$', views.OrderListView.as_view(), name='order_list'),
    url(r'^meus-pedidos/(?P<pk>\d+)/$', views.OrderDetailView.as_view(), name='order_detail'),
]

django_ecommerce/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.contrib.auth.views import LoginView, LogoutView

from core import views
from catalog import views as catalog_views


urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^contato/$', views.contact, name='contact'),
    url(r'^login/', LoginView.as_view(template_name='login.html'), name='login'),
    url(r'^logout/', LogoutView.as_view(next_page='index'), name='logout'),
    url(r'^catalogo/', include(('catalog.urls', 'catalog'), namespace='catalog')),
    url(r'^conta/', include(('users.urls', 'accounts'), namespace='accounts')),
    url(r'^compras/', include(('checkout.urls', 'checkout'), namespace='checkout')),
    url(r'^admin/', admin.site.urls),
]

users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^alterar-usuario/$', views.UpdateUserView.as_view(), name='update_user'),
    url(r'^alterar-senha/$', views.UpdatePasswordView.as_view(), name='update_password'),
    url(r'^cadastro/', views.SignupView.as_view(), name='signup')
]

checkout/models.py
from django.db import models
from django.conf import settings
from django.db.models import Sum, F

from catalog.models import Product
from core.models import IndexedTimeStampedModel

class CartItemManager(models.Manager):
    def add_item(self, cart_id, product):
        if self.filter(cart_id=cart_id, product=product).exists():
            created = False
            cart_item = self.get(cart_id=cart_id, product=product)
            cart_item.quantity = cart_item.quantity + 1
            cart_item.save()
        else:
            created = True
            cart_item = CartItem.objects.create(cart_id=cart_id, product=product, price=product.price)
        return cart_item, created

class CartItem(models.Model):
    cart_id = models.CharField('Chave do carrinho', max_length=40, db_index=True)
    product = models.ForeignKey('catalog.Product', verbose_name='Produto', on_delete=models.CASCADE)
    quantity = models.IntegerField('Quantidade', default=1)
    price = models.DecimalField('Preço', decimal_places=2, max_digits=8)

    objects = CartItemManager()

    class Meta:
        verbose_name = 'Item do Carrinho'
        verbose_name_plural = 'Itens do Carrinho'
        unique_together = (('cart_id', 'product'),)

    def __str__(self):
        return f'{self.product} [{self.quantity}]'

class OrderManager(models.Manager):
    def create_order(self, user, cart_items):
        order = self.create(user=user)
        for cart_item in cart_items:
            order_item = OrderItem.objects.create(
                order=order, quantity=cart_item.quantity, product=cart_item.product,
                price=cart_item.price
            )
        return order

class Order(IndexedTimeStampedModel):
    STATUS_CHOICES = (
        (0, 'Aguardando Pagamento'),
        (1, 'Concluída'),
        (2, 'Cancelada'),
    )

    PAYMENT_OPTION_CHOICES = (
        ('deposit', 'Depósito'),
        ('pagseguro', 'PagSeguro'),
        ('paypal', 'Paypal'),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='Usuário', on_delete=models.CASCADE)
    status = models.IntegerField('Situação', choices=STATUS_CHOICES, default=0, blank=True)
    payment_option = models.CharField('Opção de pagamento', choices=PAYMENT_OPTION_CHOICES, max_length=20, default='deposit')

    objects = OrderManager()

    class Meta:
        verbose_name = 'Pedido'
        verbose_name_plural = 'Pedidos'

    def __str__(self):
        return f'Pedido #{self.pk}'

    def products(self):
        products_ids = self.items.values_list('product')
        return Product.objects.filter(pk__in=products_ids)

    def total(self):
        aggregate_queryset = self.items.aggregate(
            total=Sum(F('price') * F('quantity'), output_field=models.DecimalField())
        )
        return aggregate_queryset['total']

class OrderItem(models.Model):
    order = models.ForeignKey(Order, verbose_name='Pedido', related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey('catalog.Product', verbose_name='Produto', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField('Quantidade', default=1)
    price = models.DecimalField('Preço', decimal_places=2, max_digits=8)

    class Meta:
        verbose_name = 'Item do pedido'
        verbose_name_plural = 'Itens do pedido'

    def __str__(self):
        return f'[{self.order}] {self.product}'

def post_save_cart_item(instance, **kwargs):
    if instance.quantity < 1:
        instance.delete()

models.signals.post_save.connect(
    post_save_cart_item, sender=CartItem, dispatch_uid='post_save_cart_item'
)

catalog/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic

from .models import Product, Category

class ProductListView(generic.ListView):

    model = Product
    template_name = 'catalog/product_list.html'
    paginate_by = '6'

class CategoryListView(generic.ListView):

    template_name = 'catalog/category.html'
    context_object_name = 'product_list'
    paginate_by = '6'

    def get_queryset(self):
        return Product.objects.filter(category__slug=self.kwargs['slug'])

    def get_context_data(self, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        context['current_category'] = get_object_or_404(Category, slug=self.kwargs['slug'])
        return context

class DetailProductView(generic.DetailView):

    model = Product
    template_name = 'catalog/product.html'

checkout/views.py
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import RedirectView, TemplateView, ListView, DetailView
from django.forms import modelformset_factory
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin

from catalog.models import Product

from .models import CartItem, Order

class CreateCartItemView(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        product = get_object_or_404(Product, slug=self.kwargs['slug'])
        if self.request.session.session_key is None:
            self.request.session.save()
        cart_item, created = CartItem.objects.add_item(self.request.session.session_key, product)
        if created:
            messages.success(self.request, 'Item adicionado com sucesso')
        else:
            messages.success(self.request, 'Item atualizado com sucesso')
        return reverse('checkout:cart_item')

class CartItemView(TemplateView):
    template_name = 'checkout/cart.html'

    def get_formset(self, clear=False):
        CartItemFormSet = modelformset_factory(CartItem, fields=('quantity',), can_delete=True, extra=0)
        session_key = self.request.session.session_key
        if session_key:
            if clear:
                formset = CartItemFormSet(queryset=CartItem.objects.filter(cart_id=session_key))
            else:
                formset = CartItemFormSet(queryset=CartItem.objects.filter(cart_id=session_key), data=self.request.POST or None)
        else:
            formset = CartItemFormSet(queryset=CartItem.objects.none())
        return formset

    def get_context_data(self, **kwargs):
        context = super(CartItemView, self).get_context_data(**kwargs)
        context['formset'] = self.get_formset()
        return context

    def post(self, request, *args, **kwargs):
        formset = self.get_formset()
        context = self.get_context_data(**kwargs)
        if formset.is_valid():
            formset.save()
            messages.success(request, 'Carrinho atualizado com sucesso.')
            context['formset'] = self.get_formset(clear=True)
        return self.render_to_response(context)

class CheckoutView(LoginRequiredMixin, TemplateView):
    template_name = 'checkout/checkout.html'

    def get(self, request, *args, **kwargs):
        session_key = request.session.session_key
        if session_key and CartItem.objects.filter(cart_id=session_key).exists():
            cart_items = CartItem.objects.filter(cart_id=session_key)
            order = Order.objects.create_order(user=request.user, cart_items=cart_items)
        else:
            messages.info(request, 'O carrinho está vazio.')
            return redirect('checkout:cart_item')
        return super(CheckoutView, self).get(request, *args, **kwargs)

class OrderListView(LoginRequiredMixin, ListView):
    template_name = 'checkout/order_list.html'
    paginate_by = 6

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)

class OrderDetailView(LoginRequiredMixin, DetailView):
    template_name = 'checkout/order_detail.html'

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)

checkout/templates/checkout/cart.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}
  Carrinho de compras
{% endblock  %}

{% block container %}
<ol class="breadcrumb">
  <li><a href="{% url 'index' %}">Início</a></li>
  <li class="active">Carrinho de Compras</li>
</ol>
<div class="page-header">
  <h1>Carrinho de Compras</h1>
</div>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <form class="" action="" method="post">
      {% csrf_token %}
      {{ formset.management_form }}
      <table class="table table-bordered">
        <thead>
          <th>
              ID
          </th>
          <th>
              Nome
          </th>
					<th>
            Preço
          </th>
          <th style="width: 10%;">
              Quantidade
          </th>
          <th>

          </th>
        </thead>
        <tbody>
        {% for form in formset %}
          <tr>
            <td>
                {{ form.instance.product.pk }}
            </td>
            <td>
                {{ form.instance.product }}
            </td>
            <td>
                R$ {{ form.instance.price|floatformat:"2" }}
            </td>
						<td>
              {% render_field form.quantity class='form-control' %}
            </td>
						<td class="text-center">
							<button name="{{ form.DELETE.html_name }}" value="on" type="submit" class="btn btn-danger btn-sm">Remover</button>
              {{ form.id }}
						</td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
      <p class="text-right">
			  <a href="{% url 'catalog:product_list' %}" class="pull-left btn btn-default">Continuar Compras</a>
			  <button type="submit" class="btn btn-primary" name="button">Atualizar Carrinho</button></li>
			  <a href="{% url 'checkout:checkout' %}" class="btn btn-success">Finalizar Compra</a>
      </p>
    </form>
  </div>
</div>
{% endblock  %}

checkout/templates/checkout/checkout.html
{% extends "base.html" %}

{% block title %}
  Finalização da compra
{% endblock  %}

{% block container %}
<ol class="breadcrumb">
  <li><a href="{% url 'index' %}">Início</a></li>
  <li><a href="{% url 'checkout:cart_item' %}">Carrinho de Compras</a></li>
  <li class="active">Finalização de Compra</li>
</ol>
<div class="page-header">
  <h1>Finalização da Compra</h1>
</div>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="alert alert-success">
      Seu pedido foi realizado com sucesso!
    </div>
    <p>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
    </p>
  </div>
</div>
{% endblock  %}

checkout/templates/checkout/order_detail.html
{% extends "users/index.html" %}

{% load pagination %}

{% block title %}
Pedido #{{ order.pk }}
{% endblock %}

{% block users_container %}
<h2>Pedido #{{ order.pk }}</h2>
<dl class="dl-horizontal">
    <dt>Total R$</dt>
    <dd>{{ order.total|floatformat:"2" }}</dd>
    <dt>Situação</dt>
    <dd>{{ object.get_status_display }}</dd>
    <dt>Data</dt>
    <dd>{{ object.created|date:"d/m/Y H:i" }}</dd>
    <dt>Meio de Pagamento</dt>
    <dd>{{ object.get_payment_option_display }}</dd>
</dl>
<h3>Itens do Pedido</h3>
{% for item in object.items.all %}
    <dl class="dl-horizontal">
        <dt>Produto</dt>
        <dd>{{ item.product }}</dd>
        <dt>Quantidade</dt>
        <dd>{{ item.quantity }}</dd>
        <dt>Preço</dt>
        <dd>{{ item.price|floatformat:"2" }}</dd>
    </dl>
{% endfor %}
{% endblock %}

checkout/templates/checkout/order_list.html
{% extends "users/index.html" %}

{% load pagination %}

{% load widget_tweaks %}

{% block title %}Meus Pedidos{% endblock %}

{% block users_container %}
<h2>Meus Pedidos</h2>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>
                ID
            </th>
            <th>
                Produtos
            </th>
            <th>
                Situação
            </th>
            <th>
                Data
            </th>
        </tr>
    </thead>
    <tbody>
        {% for order in object_list %}
        <tr>
            <td>
                <a href="{% url 'checkout:order_detail' order.pk %}">#{{ order.pk }}</a>
            </td>
            <td>
                {% for product in order.products %}
                    {{ product.name }}{% if not forloop.last %}</br> {% endif %}
                {% endfor %}
            </td>
            <td>
                {{ order.get_status_display }}
            </td>
            <td>
                {{ order.created|date:"d/m/Y" }}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% pagination request paginator page_obj %}
{% endblock %}