django_ecommerce/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.contrib.auth.views import LoginView, LogoutView

from core import views
from catalog import views as catalog_views


urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^contato/$', views.contact, name='contact'),
    url(r'^login/', LoginView.as_view(template_name='login.html'), name='login'),
    url(r'^logout/', LogoutView.as_view(next_page='index'), name='logout'),
    url(r'^catalogo/', include(('catalog.urls', 'catalog'), namespace='catalog')),
    url(r'^conta/', include(('users.urls', 'accounts'), namespace='accounts')),
    url(r'^compras/', include(('checkout.urls', 'checkout'), namespace='checkout')),
    url(r'^admin/', admin.site.urls),
]

users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^alterar-usuario/$', views.UpdateUserView.as_view(), name='update_user'),
    url(r'^alterar-senha/$', views.UpdatePasswordView.as_view(), name='update_password'),
    url(r'^cadastro/', views.SignupView.as_view(), name='signup')
]

users/models.py
import re

from django.db import models
from django.core import validators
from django.contrib.auth.models import AbstractBaseUser, UserManager, PermissionsMixin

class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(
        'Apelido / Usuário', max_length=30, unique=True, validators=[
            validators.RegexValidator(
                re.compile('^[\w.@+-]+$'),
                'Informe um nome de usuário válido. '
                'Este valor deve conter apenas letras, números '
                'e os caracteres: @/./+/-/_ .'
                , 'invalid'
            )
        ], help_text='Um nome curto que será usado para identificá-lo de forma única.'
    )
    name = models.CharField('Nome', max_length=100, blank=True)
    email = models.EmailField('Email', unique=True)
    is_staff = models.BooleanField('Equipe', default=False)
    is_active = models.BooleanField('Ativo', default=True)
    date_joined = models.DateTimeField('Data de ingresso', auto_now_add=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    objects = UserManager()

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'

    def __str__(self):
        return self.name or self.username

    def get_full_name(self):
        return str(self)

    def get_short_name(self):
        return str(self).split(" ")[0]

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms

from .models import User

class UserAdminCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email']

class UserAdminForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'name', 'is_active', 'is_staff']

users/views.py
from django.shortcuts import render
from django.views.generic import CreateView, TemplateView, UpdateView, FormView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import PasswordChangeForm

from .models import User
from .forms import UserAdminCreationForm

class IndexView(LoginRequiredMixin, TemplateView):
    template_name = 'users/index.html'

class SignupView(CreateView):
    model = User
    template_name = 'users/signup.html'
    form_class = UserAdminCreationForm
    success_url = reverse_lazy('index')

class UpdateUserView(LoginRequiredMixin, UpdateView):
    model = User
    template_name = 'users/update_user.html'
    fields = ['name', 'email']
    success_url = reverse_lazy('accounts:index')

    def get_object(self):
        return self.request.user

class UpdatePasswordView(LoginRequiredMixin, FormView):
    template_name = 'users/update_password.html'
    success_url = reverse_lazy('accounts:index')
    form_class = PasswordChangeForm

    def get_form_kwargs(self):
        kwargs = super(UpdatePasswordView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.save()
        return super(UpdatePasswordView, self).form_valid(form)

users/templates/users/index.html
{% extends "base.html" %}

{% block title %}
  Minha Conta
{% endblock %}

{% block container %}
<ol class="breadcrumb">
  <li><a href="{% url 'accounts:index' %}">Início</a></li>
  <li class="active">Minha Conta</li>
</ol>
<div class="row">
    <div class="col-md-4">
        <div class="list-group">
          <a href="{% url 'accounts:index' %}" class="list-group-item active">Minha Conta</a>
          <a href="{% url 'accounts:update_user' %}" class="list-group-item">Alterar Dados</a>
          <a href="{% url 'accounts:update_password' %}" class="list-group-item">Alterar Senha</a>
          <a href="{% url 'checkout:order_list' %}" class="list-group-item">Meus Pedidos</a>
        </div>
    </div>
    <div class="col-md-8">
    {% block users_container %}
      <h2>Bem vindo {{ user }}</h2>
    {% endblock %}
    </div>
</div>
{% endblock  %}

users/templates/users/signup.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}
  Cadastrar | {{ block.super }}
{% endblock  %}

{% block container %}
<div class="row">
  <div class="col-md-8 col-md-offset-2">
      <div class="page-header">
          <h1>Cadastrar</h1>
      </div>
      <form class="form-horizontal" method="post">
          {% csrf_token %}
          {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
              {{ error }}
            </div>
          {% endfor %}
          <fieldset>
              {% for field in form %}
                <div class="form-group{% if field.errors %} has-error{% endif %}">
                  <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
                  <div class="col-md-9">
                    {% render_field field class="form-control" %}
                    {% for error in field.errors %}
                      <span class="help-block">{{ error }}</span>
                    {% endfor %}
                  </div>
                </div>
              {% endfor %}
              <div class="form-group">
                <div class="col-md-9 col-md-offset-3">
                  <button type="submit" class="btn btn-primary">Cadastrar</button>
                </div>
              </div>
          </fieldset>
      </form>
  <div>
</div>
{% endblock  %}

users/templates/users/update_password.html
{% extends "users/index.html" %}

{% load widget_tweaks %}

{% block title %}
  Alterar Senha
{% endblock  %}

{% block users_container %}
  <h2>Alterar Senha</h2>
  <form class="form-horizontal" action="" method="post">
    {% csrf_token %}
    <fieldset>
        {% for field in form %}
        <div class="form-group{% if field.errors %} has-error{% endif %}">
          <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
          <div class="col-md-9">
            {% render_field field class='form-control' %}
            {% for error in field.errors %}
            <span class="help-block">{{ error }}</span>
            {% endfor %}
          </div>
        </div>
        {% endfor %}
        <div class="form-group">
          <div class="col-md-9 col-md-offset-3">
            <button type="submit" class="btn btn-primary">Salvar</button>
          </div>
        </div>
    </fieldset>
  </form>
{% endblock  %}

users/templates/users/update_user.html
{% extends "users/index.html" %}

{% load widget_tweaks %}

{% block title %}
  Alterar Dados
{% endblock  %}

{% block users_container %}
  <h2>Alterar Dados</h2>
  <form class="form-horizontal" action="" method="post">
    {% csrf_token %}
    <fieldset>
        {% for field in form %}
        <div class="form-group{% if field.errors %} has-error{% endif %}">
          <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
          <div class="col-md-9">
            {% render_field field class='form-control' %}
            {% for error in field.errors %}
            <span class="help-block">{{ error }}</span>
            {% endfor %}
          </div>
        </div>
        {% endfor %}
        <div class="form-group">
          <div class="col-md-9 col-md-offset-3">
            <button type="submit" class="btn btn-primary">Salvar</button>
          </div>
        </div>
    </fieldset>
  </form>
{% endblock  %}